spring.application.name=birmarket

spring.datasource.url=jdbc:postgresql://localhost:5433/birmarket
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.secret=birmarket-secret-key-should-be-at-least-256-bits-long-dont-share-this
jwt.expiration=86400000

logging.level.com.birmarket=DEBUG
logging.level.org.springframework.security=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html

iyzico.api-key=sandbox-jFadmcTMI0kjVYlFjoMolDOuoVpu71Jc
iyzico.secret-key=k9GbWNGezjjPXvqshkJkFpl96YzXOOKP
iyzico.base-url=https://sandbox-api.iyzipay.com

minio.endpoint=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket=birmarket
